import { useEffect, useState } from 'react'
import { staffApi } from '../../../api/staffApi'
import { staffAttendanceApi } from '../../../api/staffAttendanceApi'
import { useNotificationContext } from '../../../context/NotificationContext'

export default function StaffAttendance() {
  const { notify } = useNotificationContext(); const [staff, setStaff] = useState([]); const [records, setRecords] = useState([])
  const [date, setDate] = useState(new Date().toISOString().slice(0, 10)); const [statuses, setStatuses] = useState({})
  const load = async () => { try { const [s, r] = await Promise.all([staffApi.list({ limit: 100 }), staffAttendanceApi.list({ date })]); const people = s.data?.data || s.data || []; setStaff(people); setRecords(r.data || []); setStatuses(Object.fromEntries((r.data || []).map(x => [x.staffId, x.status]))) } catch { notify('Could not load staff attendance.', 'error') } }
  useEffect(() => { load() }, [date])
  const save = async () => { try { await staffAttendanceApi.mark({ date, records: staff.map(s => ({ staffId: s.id, status: statuses[s.id] || 'PRESENT' })) }); notify('Staff attendance saved.', 'success'); load() } catch { notify('Could not save staff attendance.', 'error') } }
  return <div className="space-y-6"><div className="card p-6 flex flex-wrap items-center justify-between gap-4"><div><p className="font-display text-xl font-semibold text-ink">Staff Attendance</p><p className="mt-1 text-sm text-ink-soft">Daily attendance for employees, kept separately from student records.</p></div><div className="flex gap-3"><input className="rounded-lg border border-line px-3 py-2 text-sm" type="date" value={date} onChange={e => setDate(e.target.value)} /><button onClick={save} className="rounded-lg bg-brand-600 px-4 py-2 text-sm font-medium text-white">Save attendance</button></div></div><div className="card overflow-hidden"><table className="min-w-full text-left text-sm"><thead className="bg-surface-tint text-xs font-mono uppercase text-ink-soft"><tr><th className="px-5 py-3">Employee</th><th className="px-5 py-3">Designation</th><th className="px-5 py-3">Status</th></tr></thead><tbody className="divide-y divide-line">{staff.map(s => <tr key={s.id}><td className="px-5 py-3.5 font-medium text-ink">{s.user?.name}</td><td className="px-5 py-3.5 text-ink-soft">{s.designation}</td><td className="px-5 py-3.5"><select className="rounded-lg border border-line px-2 py-1.5" value={statuses[s.id] || 'PRESENT'} onChange={e => setStatuses(v => ({ ...v, [s.id]: e.target.value }))}>{['PRESENT','ABSENT','LATE','LEAVE'].map(x => <option key={x}>{x}</option>)}</select></td></tr>)}{!staff.length && <tr><td colSpan="3" className="px-5 py-6 text-center text-ink-soft">No employees found.</td></tr>}</tbody></table></div></div>
}
